"use strict";
const THREE_LETTER_WORDS = [
    "go", "do", "be", "is", "it", "at", "of", "or", "an", "as", "by", "if", "no", "so",
    "up", "us", "we", "he", "me", "my", "am", "ax", "ox", "hi", "the", "and", "are",
    "not", "you", "all", "any", "can", "had", "her", "was", "one", "our", "day", "get",
    "has", "him", "his", "how", "man", "new", "now", "old", "two", "way", "who", "boy",
    "did", "its", "let", "put", "say", "she", "too", "dad", "mom", "cat", "dog", "run",
    "sun", "fun", "big", "red", "yes", "top", "bad", "box", "car", "cup", "eat", "end",
    "eye", "far", "few", "fly", "god", "got", "gun", "hot", "job", "key", "law", "leg",
    "lot", "low", "map", "win", "run", "act", "see", "for", "set", "but", "use", "out",
    "six", "tax", "way", "may", "ray", "bay", "hay", "joy", "toy", "cry", "dry", "fry",
    "try", "sly", "sky", "spy", "shy", "why", "zoo", "boo", "coo", "moo", "woo", "add",
    "cut", "buy", "die", "lie", "tie", "fit", "hit", "sit", "bit", "lit", "mix", "fix",
    "tax", "wax", "pay", "lay"
];
const WORDS = [
    "species", "practice", "natural", "measure", "present", "form", "order", "quality",
    "condition", "state", "action", "element", "part", "division", "subject", "ground",
    "power", "station", "register", "person", "place", "ordinary", "strong", "under",
    "make", "light", "exercise", "exchange", "parallel", "charge", "support", "judgment",
    "substance", "figure", "strength", "sound", "service", "quantity", "standard", "right",
    "point", "character", "strike", "discharge", "force", "return", "spring", "square",
    "between", "without", "water", "spirit", "distance", "contract", "positive", "position",
    "straight", "moderate", "double", "superior", "certain", "compound", "interest",
    "language", "passage", "business", "through", "manner", "relation", "general", "process",
    "strain", "delicate", "bearing", "property", "advance", "account", "original", "religion",
    "round", "over", "principal", "sharp", "surface", "line", "degree", "report", "course",
    "matter", "sentence", "body", "express", "close", "quarter", "head", "negative", "take",
    "plant", "argument", "increase", "house", "movement", "table", "balance", "separate",
    "small", "back", "entrance", "settle", "reason", "machine", "common", "material", "scale",
    "authority", "capable", "anything", "regular", "stock", "break", "opposite", "into",
    "distress", "work", "standing", "cross", "color", "number", "stroke", "convert", "radical",
    "relative", "function", "stand", "press", "question", "peculiar", "progress", "together",
    "touch", "capacity", "physical", "horse", "specific", "external", "produce", "incapable",
    "passion", "represent", "promise", "tender", "issue", "family", "range", "domestic",
    "shoulder", "change", "approach", "transfer", "carriage", "feeling", "security", "something",
    "direction", "pressure", "frame", "like", "free", "company", "inferior", "distinct",
    "variety", "solution", "capital", "grain", "deposit", "circular", "receive", "pleasure",
    "particular", "office", "faculty", "motion", "personal", "country", "narrow", "occasion",
    "open", "addition", "second", "complete", "short", "ancient", "contrary", "serve",
    "disorder", "crown", "mark", "weight", "large", "white", "tongue", "mountain", "address",
    "vessel", "throw", "science", "system", "turn", "object", "temper", "internal", "base",
    "pass", "familiar", "principle", "another", "that", "hold", "compass", "pitch", "influence",
    "enter", "command", "reduce", "level", "surprise", "time", "bottom", "face", "flower",
    "extreme", "raise", "purpose", "nature", "answer", "down", "against", "stick", "clear",
    "record", "article", "discourse", "string", "shell", "side", "fall", "backward", "determine",
    "several", "forward", "period", "absolute", "taste", "draw", "waste", "running", "spread",
    "chamber", "cause", "official", "province", "flat", "instrument", "native", "conduct",
    "maintain", "descent", "block", "presence", "simple", "lead", "weather", "direct", "which",
    "opinion", "justice", "guard", "master", "appearance", "season", "regard", "check", "shoot",
    "society", "liquid", "rule", "pattern", "sphere", "directly", "cast", "life", "definite",
    "private", "give", "knowledge", "cover", "weak", "draught", "section", "sovereign", "stop",
    "organic", "screw", "violence", "decision", "render", "beat", "rise", "current", "affection",
    "evidence", "great", "court", "silver", "hand", "correct", "roll", "honor", "wind", "plate",
    "channel", "single", "keep", "heat", "cylinder", "divide", "release", "after", "respect",
    "military", "stomach", "some", "root", "timber", "structure", "school", "exterior", "syllable",
    "piece", "feather", "pledge", "supply", "christian", "branch", "religious", "necessary",
    "father", "execution", "affected", "knot", "carry", "other", "circle", "kind", "worship",
    "style", "example", "effect", "obscure", "well", "violent", "horn", "english", "drive",
    "outside", "better", "church", "mixture", "with", "equal", "reproach", "bear", "volatile",
    "equivalent", "slender", "remove", "being", "preserve", "grace", "earth", "elevation",
    "design", "stream", "furnish", "dress", "little", "writing", "spiritual", "black", "twist",
    "picture", "from", "smooth", "estate", "fine", "anchor", "joint", "heart", "expression",
    "reach", "center", "contest", "trust", "special", "shall", "friend", "high", "call", "train",
    "traverse", "irregular", "wrong", "sign", "watch", "catch", "animal", "stone", "dependent",
    "before", "relief", "thought", "fortune", "will", "active", "formation", "valuable", "soft",
    "about", "operation", "bank", "heavy", "solid", "ring", "proportion", "symbol", "opposition",
    "apparent", "abstract", "portion", "dignity", "revolution", "post", "voluntary", "length",
    "market", "harmony", "prepare", "perform", "land", "board", "shaft", "neglect", "iron",
    "value", "attempt", "hard", "judge", "proper", "mouth", "moral", "district", "interior"
];
